<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ModularSaaS.Application</RootNamespace>
    <AssemblyName>ModularSaaS.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\ModularSaaS.Domain.csproj" />
    <ProjectReference Include="..\Plugins\Security\ModularSaaS.Security.Abstractions\ModularSaaS.Security.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mapster" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ModularSaaS.Infrastructure</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ModularSaaS.Architecture.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
