<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ModularSaaS.Security.Core</RootNamespace>
    <AssemblyName>ModularSaaS.Security.Core</AssemblyName>
    <Description>Core cryptographic engines, token handlers, and password hashers.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModularSaaS.Security.Abstractions\ModularSaaS.Security.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
  </ItemGroup>

</Project>
