#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Validate commit message format with commitlint
if [ -f "ModularSaaS/apps/Web/commitlint.config.js" ]; then
  npx --prefix ModularSaaS/apps/Web commitlint --config ModularSaaS/apps/Web/commitlint.config.js --edit "$1"
fi
